# Site settings
# These are used to personalize your new site.
title: Adam Thiemann # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  Senior Network Engineer
  Ex- Special Operations
  Billy Graham Evangelistic Association<br />
  <br /><br />
  <a href="https://1drv.ms/w/s!Aofa4H6h1GyzgY4hxIBBBozBOdv-Tw?e=qusBpY">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/adam-thiemann/">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  adamrt918 # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

